// Coordenadas aproximadas (centroides) de cada estado de México normalizadas
// a un canvas 100×60 (relación de aspecto simplificada). El frontend las
// escala al tamaño del contenedor del mapa. Sin dependencias externas.
export const MX_STATE_COORDS: Record<string, { x: number; y: number; name: string }> = {
  BC:   { x: 8,  y: 12, name: "Baja California" },
  BCS:  { x: 14, y: 27, name: "Baja California Sur" },
  SON:  { x: 24, y: 15, name: "Sonora" },
  CHIH: { x: 34, y: 15, name: "Chihuahua" },
  COAH: { x: 48, y: 19, name: "Coahuila" },
  NL:   { x: 55, y: 22, name: "Nuevo León" },
  TAM:  { x: 60, y: 28, name: "Tamaulipas" },
  SIN:  { x: 28, y: 27, name: "Sinaloa" },
  DGO:  { x: 40, y: 27, name: "Durango" },
  ZAC:  { x: 46, y: 32, name: "Zacatecas" },
  SLP:  { x: 52, y: 34, name: "San Luis Potosí" },
  NAY:  { x: 34, y: 34, name: "Nayarit" },
  AGS:  { x: 46, y: 36, name: "Aguascalientes" },
  JAL:  { x: 40, y: 38, name: "Jalisco" },
  GTO:  { x: 50, y: 40, name: "Guanajuato" },
  QRO:  { x: 54, y: 41, name: "Querétaro" },
  HGO:  { x: 56, y: 43, name: "Hidalgo" },
  VER:  { x: 62, y: 44, name: "Veracruz" },
  COL:  { x: 40, y: 42, name: "Colima" },
  MICH: { x: 45, y: 43, name: "Michoacán" },
  MEX:  { x: 55, y: 45, name: "Estado de México" },
  CDMX: { x: 56, y: 46, name: "Ciudad de México" },
  MOR:  { x: 56, y: 47, name: "Morelos" },
  TLAX: { x: 58, y: 45, name: "Tlaxcala" },
  PUE:  { x: 58, y: 47, name: "Puebla" },
  GRO:  { x: 50, y: 50, name: "Guerrero" },
  OAX:  { x: 60, y: 53, name: "Oaxaca" },
  TAB:  { x: 68, y: 50, name: "Tabasco" },
  CHIS: { x: 72, y: 55, name: "Chiapas" },
  CAM:  { x: 76, y: 48, name: "Campeche" },
  YUC:  { x: 80, y: 42, name: "Yucatán" },
  QROO: { x: 86, y: 46, name: "Quintana Roo" },
};
